# Generated by Django 2.1.7 on 2019-04-09 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=60)),
                ('short_name', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_assigned_end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Occupancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('middle_initial', models.CharField(max_length=1)),
                ('age', models.SmallIntegerField()),
                ('sex', models.CharField(max_length=1)),
                ('region', models.CharField(max_length=6)),
                ('province', models.CharField(max_length=6)),
                ('city', models.CharField(blank=True, max_length=6, null=True)),
                ('diagnosis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Diagnosis')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=20)),
                ('capacity', models.SmallIntegerField()),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Building')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('assigned_end_date', models.DateTimeField()),
                ('actual_end_date', models.DateTimeField(blank=True, null=True)),
                ('is_ongoing', models.NullBooleanField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Watcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='occupancy',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Room'),
        ),
        migrations.AddField(
            model_name='occupancy',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Visit'),
        ),
        migrations.AddField(
            model_name='occupancy',
            name='watcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Watcher'),
        ),
        migrations.AddField(
            model_name='extension',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Visit'),
        ),
    ]
