<<<<<<< HEAD
# Generated by Django 2.1.7 on 2019-04-09 14:54
=======
# Generated by Django 2.1.7 on 2019-04-09 14:59
>>>>>>> 40fc9f8d4ab1fbbdaf474bdc48e748048d2b8bcb

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='capacity',
        ),
    ]
