# Generated by Django 2.1.7 on 2019-04-09 15:07

from django.db import migrations

diagnoses = (
    'kulang sa gugma',
    'cancer ng lipunan',
    'dakogmatascosis',
    'pirminti ma sinko syndrome',
)

patients = (
    ('James', 'K', 'Bond', 13, 'm', None, '101304'),
    ('Chingg', 'Q', 'Chongg', 24, 'f', None, '09830'),
    ('Mang', 'A', 'Juan', 56, 'm', None, '118204000'),
    ('Charmaine', 'T', 'Dela Char', 8, 'f', None, '137603000'),
)

def create_diagnoses(apps, schema_editor):
    d = apps.get_model('main', 'Diagnosis')
    for diag in diagnoses:
        d(full_name=diag).save()

def create_patients(apps, schema_editor):
    p = apps.get_model('main', 'Patient')
    for pat in patients:
        p(first_name=pat[0], middle_initial=pat[1], last_name=pat[2], 
            age=pat[3], sex=pat[4], diagnosis=pat[5],
            region=pat[6][:2], province=pat[6][:4], city=pat[6][:6]).save()

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_room_capacity'),
    ]

    operations = [
        migrations.RunPython(create_diagnoses),
        migrations.RunPython(create_patients),
    ]
