# Generated by Django 2.1.7 on 2019-04-12 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_room_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occupancy',
            name='watcher',
        ),
        migrations.AddField(
            model_name='occupancy',
            name='watcher',
            field=models.ManyToManyField(to='main.Watcher'),
        ),
    ]
