# Generated by Django 2.1.7 on 2019-05-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190412_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='display_name',
        ),
        migrations.AddField(
            model_name='room',
            name='display_number',
            field=models.PositiveSmallIntegerField(default=999),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.TextField(max_length=30),
        ),
    ]
