# Generated by Django 2.1.7 on 2019-04-09 15:07

from django.db import migrations

diagnoses = (
    'hyperFISHophilia',
    'reflexive genocide syndrome',
    'talawan ug kakarowchu',
    'flat-earther',
    'bagag nawowng',
)

patients = (
    ('Fei', 'A', 'Yin', 13, 'm', None, '101304'),
    ('Happy', 'S', 'Sad', 24, 'f', None, '09830'),
    ('Rock', 'N', 'Roll', 56, 'm', None, '118204000'),
    ('Imong', 'G', 'Mama', 42, 'm', None, '118204000'),
)



def create_diagnoses(apps, schema_editor):
    d = apps.get_model('main', 'Diagnosis')
    for diag in diagnoses:
        d(full_name=diag).save()

def create_patients(apps, schema_editor):
    p = apps.get_model('main', 'Patient')
    for pat in patients:
        p(first_name=pat[0], middle_initial=pat[1], last_name=pat[2], 
            age=pat[3], sex=pat[4], diagnosis=pat[5],
            region=pat[6][:2], province=pat[6][:4], city=pat[6][:6]).save()
            
def create_rooms(apps, schema_editor):
    r = apps.get_model('main', 'Room')
    b = apps.get_model('main', 'Building')
    main = b.objects.get(name='main')
    for i in range(20):
        r(building=main, display_name=f'Room {i}').save()
        
    ann = b.objects.get(name='annex')
    for i in range(20):
        r(building=ann, display_name=f'Room {i}').save()

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_add_building_data'),
    ]

    operations = [
        migrations.RunPython(create_diagnoses),
        migrations.RunPython(create_patients),
        migrations.RunPython(create_rooms),
    ]
