# Generated by Django 2.1.7 on 2019-05-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190518_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saved_Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved', models.NullBooleanField()),
                ('last_modified', models.DateTimeField()),
            ],
        ),
    ]
