# Generated by Django 2.1.7 on 2019-03-26 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_visit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_assigned_end_date', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='visit',
            name='diagnosis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Diagnosis'),
        ),
        migrations.AddField(
            model_name='extension',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Visit'),
        ),
    ]
