# Generated by Django 2.1.7 on 2019-06-02 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_saved_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnosis',
            options={'verbose_name_plural': 'diagnoses'},
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='short_name',
        ),
    ]
