# Generated by Django 2.1.7 on 2019-04-03 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190326_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Occupancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Room')),
            ],
        ),
        migrations.RemoveField(
            model_name='patient',
            name='middle_name',
        ),
        migrations.AddField(
            model_name='patient',
            name='middle_initial',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='building',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='full_name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='short_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='visit',
            name='diagnosis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Diagnosis'),
        ),
        migrations.AlterField(
            model_name='watcher',
            name='relationship',
            field=models.CharField(max_length=15),
        ),
        migrations.AddField(
            model_name='occupancy',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Visit'),
        ),
        migrations.AddField(
            model_name='occupancy',
            name='watcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Watcher'),
        ),
    ]
