# Generated by Django 2.1.7 on 2019-04-03 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190403_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='diagnosis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Diagnosis'),
        ),
    ]
