# Generated by Django 2.1.7 on 2019-04-09 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20190409_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='diagnosis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Diagnosis'),
        ),
    ]
