# Generated by Django 2.1.7 on 2019-02-21 12:13

from django.db import migrations
from django.contrib.auth import get_user_model
from django.db import DEFAULT_DB_ALIAS


class Migration(migrations.Migration):

    def addtestsuperuser(apps, schema_editor):
        get_user_model()._default_manager.db_manager(DEFAULT_DB_ALIAS).create_superuser('test','test@test.com','test')

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.RunPython(addtestsuperuser),
    ]
